# Generated by Django 5.1.1 on 2024-09-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoodEntry',
        ),
    ]
